/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ua.org.gostroy.guestbook.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Guestbook3 service. Represents a row in the &quot;GB_Guestbook3&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ua.org.gostroy.guestbook.model.impl.Guestbook3ModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ua.org.gostroy.guestbook.model.impl.Guestbook3Impl}.
 * </p>
 *
 * @author Sergey
 * @see Guestbook3
 * @see ua.org.gostroy.guestbook.model.impl.Guestbook3Impl
 * @see ua.org.gostroy.guestbook.model.impl.Guestbook3ModelImpl
 * @generated
 */
public interface Guestbook3Model extends BaseModel<Guestbook3>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a guestbook3 model instance should use the {@link Guestbook3} interface instead.
	 */

	/**
	 * Returns the primary key of this guestbook3.
	 *
	 * @return the primary key of this guestbook3
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this guestbook3.
	 *
	 * @param primaryKey the primary key of this guestbook3
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the guestbook ID of this guestbook3.
	 *
	 * @return the guestbook ID of this guestbook3
	 */
	public long getGuestbookId();

	/**
	 * Sets the guestbook ID of this guestbook3.
	 *
	 * @param guestbookId the guestbook ID of this guestbook3
	 */
	public void setGuestbookId(long guestbookId);

	/**
	 * Returns the group ID of this guestbook3.
	 *
	 * @return the group ID of this guestbook3
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this guestbook3.
	 *
	 * @param groupId the group ID of this guestbook3
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this guestbook3.
	 *
	 * @return the company ID of this guestbook3
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this guestbook3.
	 *
	 * @param companyId the company ID of this guestbook3
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this guestbook3.
	 *
	 * @return the user ID of this guestbook3
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this guestbook3.
	 *
	 * @param userId the user ID of this guestbook3
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this guestbook3.
	 *
	 * @return the user uuid of this guestbook3
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this guestbook3.
	 *
	 * @param userUuid the user uuid of this guestbook3
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this guestbook3.
	 *
	 * @return the user name of this guestbook3
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this guestbook3.
	 *
	 * @param userName the user name of this guestbook3
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this guestbook3.
	 *
	 * @return the create date of this guestbook3
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this guestbook3.
	 *
	 * @param createDate the create date of this guestbook3
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this guestbook3.
	 *
	 * @return the modified date of this guestbook3
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this guestbook3.
	 *
	 * @param modifiedDate the modified date of this guestbook3
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this guestbook3.
	 *
	 * @return the name of this guestbook3
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this guestbook3.
	 *
	 * @param name the name of this guestbook3
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ua.org.gostroy.guestbook.model.Guestbook3 guestbook3);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ua.org.gostroy.guestbook.model.Guestbook3> toCacheModel();

	@Override
	public ua.org.gostroy.guestbook.model.Guestbook3 toEscapedModel();

	@Override
	public ua.org.gostroy.guestbook.model.Guestbook3 toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}